CREATE INDEX CONCURRENTLY IF NOT EXISTS "bookmarks_public_created_id_idx" ON "bookmarks" USING btree ("created_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "bookmarks"."status" = 'published' and "bookmarks"."is_archived" = false and "bookmarks"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bookmarks_public_id_idx" ON "bookmarks" USING btree ("id") WHERE "bookmarks"."status" = 'published' and "bookmarks"."is_archived" = false and "bookmarks"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bookmarks_public_updated_id_idx" ON "bookmarks" USING btree ("updated_at","id") WHERE "bookmarks"."status" = 'published' and "bookmarks"."is_archived" = false and "bookmarks"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bookmarks_featured_created_id_idx" ON "bookmarks" USING btree ("created_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "bookmarks"."status" = 'published' and "bookmarks"."is_archived" = false and "bookmarks"."deleted_at" is null and "bookmarks"."is_favorite" = true;--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bookmarks_public_title_trgm_idx" ON "bookmarks" USING gin ("title" gin_trgm_ops) WHERE "bookmarks"."status" = 'published' and "bookmarks"."is_archived" = false and "bookmarks"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bookmarks_public_description_trgm_idx" ON "bookmarks" USING gin ("description" gin_trgm_ops) WHERE "bookmarks"."status" = 'published' and "bookmarks"."is_archived" = false and "bookmarks"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bookmarks_public_overview_trgm_idx" ON "bookmarks" USING gin ("overview" gin_trgm_ops) WHERE "bookmarks"."status" = 'published' and "bookmarks"."is_archived" = false and "bookmarks"."deleted_at" is null;
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "categories_name_trgm_idx" ON "categories" USING gin ("name" gin_trgm_ops);
