"use client";

import type { ReactNode } from "react";
import {
  House,
  Book,
  Code,
  Palette,
  Music,
  Video,
  Camera,
  Image,
  FileText,
  Folder,
  Database,
  Server,
  Cloud,
  Globe,
  Mail,
  MessageSquare,
  Users,
  User,
  Settings,
  Wrench,
  Zap,
  Star,
  Heart,
  ShoppingCart,
  CreditCard,
  ChartBar,
  TrendingUp,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Laptop,
  Smartphone,
  Gamepad2,
  Trophy,
  Award,
  Gift,
  Package,
  Box,
  Tag,
  Filter,
  Search,
  Bell,
  Lock,
  Shield,
  Key,
  Eye,
  EyeOff,
  Download,
  Upload,
  Share,
  Link,
  ExternalLink,
  Copy,
  Pencil,
  Trash2,
  Plus,
  Minus,
  Check,
  X,
  CircleAlert,
  Info,
  CircleHelp,
  ChevronRight,
  ChevronLeft,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChartNoAxesColumn,
  CodeXml,
  CircleX,
  SquareX,
  OctagonX,
  CircleCheck,
  CirclePlus,
  CircleMinus,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

function toKebab(name: string): string {
  return name
    .replace(/([a-zA-Z])([0-9])/g, "$1-$2") // letter→digit
    .replace(/([0-9])([a-zA-Z])/g, "$1-$2") // digit→letter (e.g. "2Plus" → "2-Plus")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2") // run-of-caps + camel tail
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2") // camelCase
    .replace(/[_\s]+/g, "-")
    .toLowerCase();
}

const ICONS: Record<string, LucideIcon> = Object.fromEntries(
  Object.entries({
    House: House,
    Book: Book,
    Code: Code,
    Palette: Palette,
    Music: Music,
    Video: Video,
    Camera: Camera,
    Image: Image,
    FileText: FileText,
    Folder: Folder,
    Database: Database,
    Server: Server,
    Cloud: Cloud,
    Globe: Globe,
    Mail: Mail,
    MessageSquare: MessageSquare,
    Users: Users,
    User: User,
    Settings: Settings,
    Wrench: Wrench,
    Zap: Zap,
    Star: Star,
    Heart: Heart,
    ShoppingCart: ShoppingCart,
    CreditCard: CreditCard,
    ChartBar: ChartBar,
    TrendingUp: TrendingUp,
    Calendar: Calendar,
    Clock: Clock,
    MapPin: MapPin,
    Phone: Phone,
    Laptop: Laptop,
    Smartphone: Smartphone,
    Gamepad2: Gamepad2,
    Trophy: Trophy,
    Award: Award,
    Gift: Gift,
    Package: Package,
    Box: Box,
    Tag: Tag,
    Filter: Filter,
    Search: Search,
    Bell: Bell,
    Lock: Lock,
    Shield: Shield,
    Key: Key,
    Eye: Eye,
    EyeOff: EyeOff,
    Download: Download,
    Upload: Upload,
    Share: Share,
    Link: Link,
    ExternalLink: ExternalLink,
    Copy: Copy,
    Pencil: Pencil,
    Trash2: Trash2,
    Plus: Plus,
    Minus: Minus,
    Check: Check,
    X: X,
    CircleAlert: CircleAlert,
    Info: Info,
    CircleHelp: CircleHelp,
    ChevronRight: ChevronRight,
    ChevronLeft: ChevronLeft,
    ArrowRight: ArrowRight,
    ArrowLeft: ArrowLeft,
    ArrowUp: ArrowUp,
    ArrowDown: ArrowDown,
    ChartNoAxesColumn: ChartNoAxesColumn,
    CodeXml: CodeXml,
    CircleX: CircleX,
    SquareX: SquareX,
    OctagonX: OctagonX,
    CircleCheck: CircleCheck,
    CirclePlus: CirclePlus,
    CircleMinus: CircleMinus,
  }).map(([name, Icon]) => [toKebab(name), Icon]),
);

const LEGACY_ALIASES: Record<string, string> = {
  home: "house",
  tool: "wrench",
  "bar-chart": "chart-bar",
  "bar-chart-3": "chart-no-axes-column",
  "code-2": "code-xml",
  edit: "pencil",
  "alert-circle": "circle-alert",
  "help-circle": "circle-help",
  "x-circle": "circle-x",
  "x-square": "square-x",
  "x-octagon": "octagon-x",
  "check-circle": "circle-check",
  "plus-circle": "circle-plus",
  "minus-circle": "circle-minus",
  "info-circle": "circle-help", // lucide collapses these onto circle-help/info
};

interface DynamicIconProps extends Omit<LucideProps, "name"> {
  name?: string | null;
  fallback?: ReactNode;
}

// Unknown imported names retain a visible generic icon. Never load the full
// lucide registry on public pages; the admin picker uses the same supported set.
export function DynamicIcon({ name, fallback, ...props }: DynamicIconProps) {
  if (!name) return <>{fallback ?? null}</>;
  const key = toKebab(name);
  const resolved = Object.hasOwn(ICONS, key) ? key : LEGACY_ALIASES[key];
  const Icon = Object.hasOwn(ICONS, resolved) ? ICONS[resolved] : undefined;
  if (!Icon) return <>{fallback ?? <Folder {...props} />}</>;
  return <Icon {...props} />;
}

export const POPULAR_ICONS = [
  "House",
  "Book",
  "Code",
  "Palette",
  "Music",
  "Video",
  "Camera",
  "Image",
  "FileText",
  "Folder",
  "Database",
  "Server",
  "Cloud",
  "Globe",
  "Mail",
  "MessageSquare",
  "Users",
  "User",
  "Settings",
  "Wrench",
  "Zap",
  "Star",
  "Heart",
  "ShoppingCart",
  "CreditCard",
  "ChartBar",
  "TrendingUp",
  "Calendar",
  "Clock",
  "MapPin",
  "Phone",
  "Laptop",
  "Smartphone",
  "Gamepad2",
  "Trophy",
  "Award",
  "Gift",
  "Package",
  "Box",
  "Tag",
  "Filter",
  "Search",
  "Bell",
  "Lock",
  "Shield",
  "Key",
  "Eye",
  "EyeOff",
  "Download",
  "Upload",
  "Share",
  "Link",
  "ExternalLink",
  "Copy",
  "Pencil",
  "Trash2",
  "Plus",
  "Minus",
  "Check",
  "X",
  "CircleAlert",
  "Info",
  "CircleHelp",
  "ChevronRight",
  "ChevronLeft",
  "ArrowRight",
  "ArrowLeft",
  "ArrowUp",
  "ArrowDown",
] as const;
